version: "3.9"
services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: staysync-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost,1433", "-U", "sa", "-P", "Your_password123", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    container_name: staysync-api
    depends_on:
      sql:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      # Your app reads this at runtime in Program.cs
      ConnectionStrings__Sql: "Server=sql,1433;Database=StaySync;User Id=sa;Password=Your_password123;Encrypt=False;TrustServerCertificate=True"
      # Optional: seed toggle (only in dev)
      Seed__Enabled: "true"
    ports:
      - "8080:8080" # host:container (matches Dockerfile)
